FROM webhippie/python:latest-amd64

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Jenkins Job Builder" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/jenkins-jobs"]

RUN apk update && \
  apk upgrade && \
  pip3 install -U pip jenkins-job-builder && \
  rm -rf /var/cache/apk/*
